pipeline:
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Github_authent
        build: <+input>
  stages:
    - stage:
        name: checkout
        identifier: checkout
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      apt-get install docker
                      apt-get install git
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: Github_authent
                    repoName: dnbtest
                    build:
                      type: branch
                      spec:
                        branch: main
  identifier: newtest_Clone
  name: newtest - Clone
